# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site setting
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jeff Doolittle
author: Jeff Doolittle
email: jeff@jeffdoolittle.com
description: >- # this means to ignore newlines until the next key
  Software Architect and Mentor
contact: You can reach me via email or through one of the social media platforms linked here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeffdoolittle.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title/
header_pages:
  - events.html
  - publications.html
  - mentoring.md
  - contact.md
  - about.md

# favicon: https://favicon.io/favicon-generator/?t=JD&ff=Covered+By+Your+Grace&fs=100&fc=%23FFF&b=rounded&bc=%2305A

show_excerpts: true

#social
twitter_username: jeffdoolittle
github_username: jeffdoolittle
linkedin_username: jeffdoolittle
facebook_username: jeffdoolittle
instagram_username: jeffdoolittle
stackoverflow_user: "627205"
youtube_username: jeffdoolittle
soundcloud_username: jeffdoolittle
jitsi_username: jeffdoolittle

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      show_banner: true
      show_recents: true
  - scope:
      path: "assets"
    values:
      image: true

# defaults:

#   - scope:
#       path: "projects"
#       type: "pages" # previously `page` in Jekyll 2.2.
#     values:
#       layout: "project" # overrides previous default layout
#       author: "Mr. Hyde"

# Google Analytics
google_analytics: UA-85204-1

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: jeffdoolittle
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
