title: Jeff Doolittle
author: Jeff Doolittle
email: jeff@jeffdoolittle.com
description: Software Architect and Mentor - I help make good software engineers great! 
contact: You can reach me via email or through one of the social media platforms linked here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeffdoolittle.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title/
header_pages:
  - events.html
  - publications.html
  - mentoring.md
  - contact.md
  - about.md
show_excerpts: true

# favicon: https://favicon.io/favicon-generator/?t=JD&ff=Covered+By+Your+Grace&fs=100&fc=%23FFF&b=rounded&bc=%2305A

#social
twitter_username: jeffdoolittle
github_username: jeffdoolittle
linkedin_username: jeffdoolittle
facebook_username: jeffdoolittle
instagram_username: jeffdoolittle
stackoverflow_user: "627205"
youtube_username: jeffdoolittle
soundcloud_username: jeffdoolittle
jitsi_username: jeffdoolittle

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      show_banner: true
      show_recents: true
      show_title: true
      img: 
        file: full_head_shot.jpg
      social:
        img: social_head_shot.jpg
  - scope:
      path: "assets"
    values:
      image: true

# Google Analytics
google_analytics: UA-85204-1

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: jeffdoolittle

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
